# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='customer_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.Order'),
            preserve_default=False,
        ),
    ]
