# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number_of_tables',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='table',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
