# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160406_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
