# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160407_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Seat',
        ),
    ]
