# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_order_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
