# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 31, 20, 27, 51, 104187, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
