# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20160413_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['seat_number']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('N', 'Non-Alcoholic Beverage'), ('A', 'Appetizer'), ('E', 'Entree'), ('D', 'Dessert'), ('B', 'Alcohol')], default='E', max_length=1),
        ),
    ]
