# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160414_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
