# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 20:08
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_restaurant_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=stdimage.models.StdImageField(default='uploads/default.png', upload_to='uploads'),
        ),
    ]
