# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20160414_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
