# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_table_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
            ],
        ),
    ]
