# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_menu_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='current_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_working_menu', to='server.Menu'),
            preserve_default=False,
        ),
    ]
