# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_restaurant_current_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number_of_seats',
            field=models.IntegerField(default=1),
        ),
    ]
